### ISSUE TITLE
Can you send me a prebuilt IPA for 13.5?

### ISSUE THREAD

**Issue by LilSizzurp** [krxdev-kaan/CSGOHackGUI#1]
I don't own a mac :/

**Comment by krxdev-kaan** [comment]
Yeah sure when i get to my mac tomorrow or the other day (im on my windows machine right now). 
I will send it to you right away.
Until then, this issue will remain open.

**Comment by krxdev-kaan** [comment]
@LilSizzurp i created the IPA with a little trick but im not sure if it's working properly. Since my enrolled developer account is not activated rn i've used a payload creation trick. If you could get it working would you tell me so i could add the file to Releases ?

**Comment by LilSizzurp** [comment]
Yeah *usually* you can't install unsigned IPAs.
*usually* ;)

**Comment by krxdev-kaan** [comment]
Soo last call is yours. Would you like to try to install the IPA through Cydia Impactor etc. or would you like to skip it ?

**Comment by LilSizzurp** [comment]
yeah ofc

**Comment by krxdev-kaan** [comment]
Sure then, sending the IPA m8.

**Comment by krxdev-kaan** [comment]
Here ya go.
https://mega.nz/file/hVkDxKCD#bSd-w44QGXmrZ_HtZOBGQjSyUduY_yK36WHHm1KRUeI

**Comment by LilSizzurp** [comment]
Alright I'll try it.

**Comment by LilSizzurp** [comment]
Incorrect entitlements, apparently.

**Comment by krxdev-kaan** [comment]
Well shit then. I'll let you know if i find any other way to extract the IPA. Or if i re-activate my enrollment which is pretty possible these days since i started to write IOS Apps again.

**Comment by LilSizzurp** [comment]
Maybe the manifest got corrupted during extraction?

**Comment by krxdev-kaan** [comment]
Nah i don't think so. I extracted the IPA to check the files inside it was looking good. It's really something about it being unsigned i guess but im searching other ways to get a IPA that works.

**Comment by LilSizzurp** [comment]
Hold on.

**Comment by LilSizzurp** [comment]
Are notifications enabled?

**Comment by krxdev-kaan** [comment]
wdym ?

**Comment by krxdev-kaan** [comment]
Okay @LilSizzurp i got the IPA working. Cydia Impactor is not working since it only installs PreSigned IPA files. But if you use AltServer you can install with no problem since it signs the IPA if it’s unsigned.

**Comment by krxdev-kaan** [comment]
Tested with 2 iphones + my windows pc.

**Comment by LilSizzurp** [comment]
ok but are notifications enabled?

**Comment by LilSizzurp** [comment]
Since that apparently causes issues in the ReProvision IPA installer module.

**Comment by krxdev-kaan** [comment]
No they aren't enabled. But i cydia impactor is not working anyways. It's really outdated + if you don't have a jailbroken phone with cydia extender. It's really impossible for it to work by this day. So please use AltServer to install the IPA because me and my friends tested it and we're using it rn. (if you wanna know how to use AltServer i can send you a video but you can find a tutorial pretty easily from it's official website anyways)

**Comment by LilSizzurp** [comment]
I am jailbroken and I use AltServer for unc0ver lol

**Comment by krxdev-kaan** [comment]
That’s weird. Are you using altserver to install the app or cydia impactor.

**Comment by krxdev-kaan** [comment]
I mean it shouldn’t matter actually since you are jailbroken and apps doesn’t need any kind of sign. (Afaik unc0ver had one of those AMFI patches)

**Comment by LilSizzurp** [comment]
I tried ReProvision but i guess i'll try altserver

**Comment by LilSizzurp** [comment]
Yeah it worked through AltServer and then resigning in ReProvision. Thanks!

**Comment by LilSizzurp** [comment]
Do you have discord btw?

**Comment by krxdev-kaan** [comment]
Cool. Lemme know the results 👍 btw i will release a new update to [AqHax-CSGO](https://github.com/krxdev-kaan/AqHax-CSGO/) in 5 minutes cause there was not a option to connect to IOS Client without changing some configurations but i added an option for ya 👍

**Comment by LilSizzurp** [comment]
..Do you have Discord?

**Comment by krxdev-kaan** [comment]
Yeah whats your name#tag ?

**Comment by LilSizzurp** [comment]
Lil Sizzurp#0001
